#!/usr/bin/env python

import os
import sys

import radicale.__main__

from etesync_dav import qtapp
from etesync_dav.manage import Manager
from etesync_dav.config import CONFIG_DIR, RADICALE_CONFIG, RADICALE_CONFIG_FILE


def manage(args):
    import argparse
    import getpass

    manager = Manager()

    def print_credentials(username, password):
        print("User: {}\nPassword: {}".format(username, password))

    parser = argparse.ArgumentParser()
    parser.add_argument("command",
                        choices=('add', 'del', 'get', 'list'),
                        help="Either add to add a user, del to remove a user, get to show login creds, " +
                             "or list to list all users.")
    parser.add_argument("username",
                        nargs='?',
                        help="The username used with EteSync")
    parser.add_argument("--login-password",
                        help="The password to login to the EteSync server.")
    parser.add_argument("--encryption-password",
                        help="The encryption password")
    args = parser.parse_args(args=args)

    if not os.path.exists(CONFIG_DIR):
        os.makedirs(CONFIG_DIR)

    if args.command == 'add':
        exists = manager.validate_username(args.username)
        if exists:
            raise RuntimeError("User already exists. Delete first if you'd like to override settings.")

        login_password = (getattr(args, 'login_password') or
                          getpass.getpass(prompt="Please enter the EteSync login password: "))
        encryption_password = (getattr(args, 'encryption_password') or
                               getpass.getpass(prompt="Please enter your encryption password: "))

        print_credentials(args.username, manager.add(args.username, login_password, encryption_password))

    elif args.command == 'del':
        print("Deleting user")
        manager.delete(args.username)

    elif args.command == 'get':
        print_credentials(args.username, manager.get(args.username))

    elif args.command == 'list':
        for user in manager.list():
            print(user)


if len(sys.argv) > 1 and sys.argv[1] == 'manage':
    manage(sys.argv[2:])
    sys.exit(0)


if len(sys.argv) > 1 and sys.argv[1] == '--version':
    import etesync_dav
    print("EteSync DAV version: ", etesync_dav.__version__)
    print("Radicale version: ", radicale.VERSION)
    sys.exit(0)

if not os.path.exists(CONFIG_DIR):
    print('Configuration not found. Please run "etesync-dav manage" first.')
    sys.exit(1)

if not os.path.exists(RADICALE_CONFIG_FILE):
    with open(RADICALE_CONFIG_FILE, "w") as f:
        f.write(RADICALE_CONFIG)


run_service = False


def set_run_service():
    global run_service
    run_service = True


if qtapp.HAS_GUI:
    qt_exit_status = qtapp.run(set_run_service)
else:
    set_run_service()
    qt_exit_status = 0


if run_service:
    os.chdir(CONFIG_DIR)
    os.environ['RADICALE_CONFIG'] = RADICALE_CONFIG_FILE

    radicale.__main__.run()

sys.exit(qt_exit_status)
